### ISSUE TITLE
Error code 413

### ISSUE THREAD

**Issue by ocaisa** [lyqht/deepl-translate-github-action#8]
This action doesn't seem to work too well for me, when I try to translate https://github.com/ocaisa/shell-novice/blob/main/episodes/01-intro.md I get
```
DeepLError: Unexpected status code: 413 Payload Too Large
```
(see https://github.com/ocaisa/shell-novice/actions/runs/6236360910/job/16927454241#step:2:519)

**Comment by ocaisa** [comment]
The size limit is 128 KiB I think, which translates to about 16K characters.

**Comment by lyqht** [comment]
Thanks for opening the issue.

If you refer to the error in the github action log that you have given, it is thrown by the deepl-node library. In other words, the size limit is imposed by DeepL API, and not by this github action. 


<details>

```
DeepLError: Unexpected status code: 413 Payload Too Large, <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
, content: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at checkStatusCode (/home/runner/work/_actions/lyqht/deepl-translate-github-action/v2/node_modules/deepl-node/dist/index.js:265:19)
```

</details>

I briefly checked your markdown, it is **21K** (21274 to be exact) characters in length.

You could try splitting your document into multiple documents instead for translation.

**Comment by lyqht** [comment]
i thought about adding a split document feature to the github action in the past, but decided against it because i won't know for sure how users prefer to split their document, such that it keeps its semantic meaning for translation. That's why for now i can only suggest to split the doc up. It's easier for your readers to read shorter docs too.

**Comment by ocaisa** [comment]
I'm trying to come up with an automated translation workflow for a community who develop lessons in Markdown, so I don't actually control the input file size.

I could use something like https://github.com/twardoch/split-markdown4gpt , but I don't know how I could inject that into this Action. I may just make a fork and tweak things for my specific use case (maybe using https://github.com/DeepLcom/deepl-node/blob/main/src/index.ts#L600 , but files come with a minium 50K character cost)

Thanks for the reply, I'll go away and think about it some more.

**Comment by lyqht** [comment]
That sounds like a really nice thing to do for the community. 

After working on the fork, you could make a PR to this repo if you ever want to!
